create table public."MyTable2" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  column1 text not null,
  column2 bigint not null,
  constraint MyTable2_pkey primary key (id)
) TABLESPACE pg_default;
