create table public."ActivateLog" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  comment text null,
  constraint ActivateLog_pkey primary key (id)
) TABLESPACE pg_default;
