create table public."MyTable1" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  column1 text null,
  column2 bigint null,
  constraint MyTable1_pkey primary key (id)
) TABLESPACE pg_default;

