name: Supabase API Access

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 */2 * *'  # 中2日ごとに0:00に起動 1, 4, 7, 10, ...
  workflow_dispatch:

jobs:
  access-supabase-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Access Supabase API
        run: |
          curl -X POST 'https://${{ secrets.SUPABASE_PROJECT_ID }}.supabase.co/rest/v1/ActivateLog' \
            -H "apikey: ${{ secrets.SUPABASE_API_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"comment": "activated by github actions"}'
      
      - name: Check Activation Log Count
        run: |
          RESPONSE=$(curl -s -X POST \
            'https://${{ secrets.SUPABASE_PROJECT_ID }}.supabase.co/rest/v1/rpc/count_activate_log' \
            -H "apikey: ${{ secrets.SUPABASE_API_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}')
          echo "ActivateLog count: $RESPONSE"
